import 'package:finsim/screens/add_expenditure_screen.dart'
    show ExpenditureFrequency;
import 'package:flutter/material.dart';
import 'package:jiffy/jiffy.dart';

class Expenditure {
  int id = 0;
  String name = '';
  ExpenditureFrequency frequency = ExpenditureFrequency.Monthly;
  int amount = 0;
  int yearlyAppreciationPercentage = 0;
  Jiffy startDate = Jiffy().startOf(Units.DAY);
  Jiffy endDate = Jiffy().startOf(Units.DAY).add(years: 100);
  bool belongsToAsset = false;
  bool belongsToLiability = false;

  Map<String, Object> toMap() {
    return {
      //Not passing id in Map so that it can be autogenerated by Sqflite
      'name': this.name,
      //Storing enum index in database
      'frequency': ExpenditureFrequency.values.indexOf(this.frequency),
      'amount': this.amount,
      'yearlyAppreciationPercentage': this.yearlyAppreciationPercentage,
      'startDate': this.startDate.format(), //ISO 8601 format
      'endDate': this.endDate.format(), //ISO 8601 format
      'belongsToAsset': belongsToAsset ? 1 : 0,
      'belongsToLiability': belongsToLiability ? 1 : 0,
    };
  }

  static Expenditure fromMap(Map<String, dynamic> map) {
    var e = Expenditure();
    e.id = map['id'];
    e.name = map['name'];
    e.frequency = ExpenditureFrequency.values[map['frequency']];
    e.amount = map['amount'];
    e.yearlyAppreciationPercentage = map['yearlyAppreciationPercentage'];
    e.startDate = Jiffy(map['startDate']);
    e.endDate = Jiffy(map['endDate']);
    e.belongsToAsset = map['belongsToAsset'] == 1 ? true : false;
    e.belongsToLiability = map['belongsToLiability'] == 1 ? true : false;

    return e;
  }

  @override
  operator ==(o) =>
      o is Expenditure &&
      o.id == id &&
      o.name == name &&
      o.frequency == frequency &&
      o.amount == amount &&
      o.yearlyAppreciationPercentage == yearlyAppreciationPercentage &&
      o.startDate.dateTime == startDate.dateTime &&
      o.endDate.dateTime == endDate.dateTime &&
      o.belongsToAsset == belongsToAsset &&
      o.belongsToLiability == belongsToLiability;

  @override
  int get hashCode => hashValues(
        id,
        name,
        frequency,
        amount,
        yearlyAppreciationPercentage,
        startDate.dateTime,
        endDate.dateTime,
        belongsToAsset,
        belongsToLiability,
      );
}
