import 'package:finsim/screens/add_expenditure_screen.dart'
    show ExpenditureFrequency;
import 'package:jiffy/jiffy.dart';

class Expenditure {
  int id = 0;
  String name = '';
  ExpenditureFrequency frequency = ExpenditureFrequency.Monthly;
  int amount = 0;
  int yearlyAppreciationPercentage = 0;
  Jiffy startDate = Jiffy().startOf(Units.DAY);
  Jiffy endDate = Jiffy({'year': 2099, 'month': 1, 'day': 1});
  bool belongsToAsset = false;

  Map<String, Object> toMap() {
    return {
      //Not passing id in Map so that it can be autogenerated by Sqflite
      'name': this.name,
      //Storing enum index in database
      'frequency': ExpenditureFrequency.values.indexOf(this.frequency),
      'amount': this.amount,
      'yearlyAppreciationPercentage': this.yearlyAppreciationPercentage,
      'startDate': this.startDate.format(), //ISO 8601 format
      'endDate': this.endDate.format(), //ISO 8601 format
      'belongsToAsset': belongsToAsset ? 1 : 0,
    };
  }

  static Expenditure fromMap(Map<String, dynamic> expenditureMap) {
    var expenditure = Expenditure();
    expenditure.id = expenditureMap['id'];
    expenditure.name = expenditureMap['name'];
    expenditure.frequency =
        ExpenditureFrequency.values[expenditureMap['frequency']];
    expenditure.amount = expenditureMap['amount'];
    expenditure.yearlyAppreciationPercentage =
        expenditureMap['yearlyAppreciationPercentage'];
    expenditure.startDate = Jiffy(expenditureMap['startDate']);
    expenditure.endDate = Jiffy(expenditureMap['endDate']);
    expenditure.belongsToAsset =
        expenditureMap['belongsToAsset'] == 1 ? true : false;

    return expenditure;
  }
}
